### ISSUE TITLE
Tank Compressor bluescreens

### ISSUE THREAD

**Issue by lunarlabs** [Skyrat-SS13/Skyrat-TG#12373]
Reporting client version: 514.1571

## Round ID:
4896

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NON-MODULAR] Small MODsuits remaster](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)

## Reproduction:

The Tank Compressor does not function at all, trying to interact brings up an NTOS blue screen:

```
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Unable to get property 'gases' of undefined or null reference
   at t.GasmixParser (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:1729349)
   at Be (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:179720)
   at De (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:180768)
   at Te (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:180607)
   at Le (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:179584)
   at Te (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:179584)
   at De (http://127.0.0.1:52951/tmp20204/tgui.bundle.js:1:180768)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"dannyglands","interface":"TankCompressor","window":{"key":"[0x200b356]-main","size":null,"fancy":1,"locked":0}}
```

**Comment by lunarlabs** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12254 does not fix.

`A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Unable to get property 'gases' of undefined or null reference
   at t.GasmixParser (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:1729149)
   at Be (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:179720)
   at De (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:180768)
   at Te (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:180607)
   at Le (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:179584)
   at Te (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:179584)
   at De (http://127.0.0.1:56919/tmp21900/tgui.bundle.js:1:180768)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"dannyglands","interface":"TankCompressor","window":{"key":"[0x200ae0b]-main","size":null,"fancy":1,"locked":0}}

Nanotrasen (c) 2525-2562 `
