### ISSUE TITLE
opening omni Tank compressor yields an error

### ISSUE THREAD

**Issue by Z0w0plankton** [Skyrat-SS13/Skyrat-TG#12393]
Reporting client version: 514.1583

## Round ID:
4906

## Testmerges:
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[NON-MODULAR] Small MODsuits remaster](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12310)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)

## Reproduction:

Simply open the interface for the omni Tank compressor (in toxins, or by making a new one, think all of them give the same error ) by clicking on it and it will return the following error:

TypeError: Unable to get property 'gases' of undefined or null reference
   at t.GasmixParser (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:1729349)
   at Be (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:179720)
   at De (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:180768)
   at Te (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:180607)
   at Le (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:179584)
   at Te (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:179584)
   at De (http://127.0.0.1:65445/tmp2140/tgui.bundle.js:1:180768)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"123neok321","interface":"TankCompressor","window":{"key":"[0x200b913]-main","size":null,"fancy":1,"locked":0}}

**Comment by Z0w0plankton** [comment]
Someone already reported this, whoops
