### ISSUE TITLE
"Lifeline" Tablet/Laptop application has ceased working

### ISSUE THREAD

**Issue by PeriwinkleBuddy** [Skyrat-SS13/Skyrat-TG#14754]
## Round ID:

 5880

## Reproduction:

 As the title suggests, opening "Lifeline" gives a NTOS bluescreen, text it pukes out as follows.

TypeError: Unable to get property 'startsWith' of undefined or null reference
   at s (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:298355)
   at Be (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179720)
   at Anonymous function (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179720)
   at Te (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179584)
   at Anonymous function (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:59798/tmp16480/tgui.bundle.js:1:179720)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"periwinkly","interface":"NtosRadar","window":{"key":"[0x210271f2]-main","size":null,"fancy":1,"locked":0}}

**Comment by ghost** [comment]
Worth noting this isnt just Lifeline, but also the nukedisc tracking app (which contractors start with. Which breaks contractor tablets if its opened)
Same bluescreen TypeError

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/14777
