### ISSUE TITLE
Fancy Chat breaks when editing highlights

### ISSUE THREAD

**Issue by wivernshy** [Skyrat-SS13/Skyrat-TG#22774]
Reporting client version: 514.1589

## Round ID:
9014

## Testmerges:
- [[SEMI-MODULAR] Roundstart delam panic button](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22145)
- [[MODULAR] Dynamic threat/midround calculation](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22409)
- [[MODULAR] Adds the option for missing a limb to the prosthetics menu](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097)
- [[MANUAL MIRROR] Robotic organ and disease improvements](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22631)
- [Hemophagus, The Hemophage Revamp, Part Four: Blood Depravity](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22625)
- [[MODULAR] Robust Adult Pref Checking](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22522)
- [[MOSTLY MODULAR] NIFSoft HUDs ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22063)

## Reproduction:

Went to add '[AI Private]" to my highlighted words in game, and clicked off of the popup to scroll up in chat.  Immediately, the entire chat window turned into the NtOS bluescreen.  Using the 'Fix chat' verb, restarting the game & BYOND, and clearing the cache all haven't resolved the issue.

> A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: SyntaxError: Expected ']' in regular expression
   at A (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:117677)
   at Anonymous function (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:248947)
   at Anonymous function (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:41113)
   at map (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:90914)
   at t.setHighlight (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:248306)
   at Anonymous function (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:239123)
   at u.dispatch (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:204604)
   at Anonymous function (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:271632)
   at Anonymous function (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:110594)
   at r (http://127.0.0.1:50845/tmp62308/tgui-panel.bundle.js:1:64891)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"wivernshy","window":{"fancy":0,"locked":0}}

Nanotrasen (c) 2525-540

**Comment by vinylspiders** [comment]
Will be fixed by this once the server updates https://github.com/Skyrat-SS13/Skyrat-tg/pull/22780
