### ISSUE TITLE
NIF Settings Screen broke

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#25576]
Reporting client version: 514.1589

## Issue Summary
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/131064729/01743788-4163-4a86-982a-43e9f276a8e6)

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 ReferenceError: 't' is undefined
   at u (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:300:15742)
   at Ka (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:66029)
   at Pl (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:120381)
   at El (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:115991)
   at nd (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:115925)
   at Qi (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:115778)
   at Tl (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:112776)
   at Ur (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:48848)
   at bs (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:113098)
   at Ht (http://127.0.0.1:55384/tmp8432/tgui.bundle.js:9:16134)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; wbxapp 1.0.0; Zoom 3.6.0)
State: {"ckey":"oh hey my ckey","interface":"NifPanel","window":{"key":"[0x202146e]-main","size":null,"fancy":1,"locked":1}}

## Round ID:
10127

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)

## Reproduction:
Have NIF, open NIF menu, click the gear to open settings.

**Comment by Shagglehod** [comment]
Bumping this, I also am having the same issue.
![uYtJrthpcU](https://github.com/Skyrat-SS13/Skyrat-tg/assets/106351544/e04a6bfb-aa73-4c80-b60c-0324948528ab)
