### ISSUE TITLE
Emojipedia bricking PDAs

### ISSUE THREAD

**Issue by wivernshy** [Skyrat-SS13/Skyrat-TG#25668]
Reporting client version: 514.1589

## Issue Summary
Attempting to open the Emojipedia app on PDAs will freeze the client and then result in an NTOS bluescreen
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/46330016/e472b950-7b95-4bce-bee1-dcadbf73c902)

Full NtOS dialogue:

> Error: Minified React error #137; visit https://reactjs.org/docs/error-decoder.html?invariant=137&args[]=img for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at wt (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:15206)
   at Zu (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:92115)
   at gu (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:115096)
   at pu (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:114854)
   at id (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:114721)
   at ms (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:114574)
   at mu (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:111600)
   at si (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:48535)
   at Mi (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:112108)
   at vd (http://127.0.0.1:54776/tmp12376/tgui.bundle.js:9:128466)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"wivernshy","interface":"NtosEmojipedia","window":{"key":"[0x2026426]-main","size":null,"fancy":1,"locked":0}}

## Round ID:
10158

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [LOOC'ing while in crit..? Or while unconscious..? You got it!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25506)

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25699 Will be fixed by this on the next server update
