### ISSUE TITLE
Company Import crashes when picking an item.

### ISSUE THREAD

**Issue by GreytideSkye** [Skyrat-SS13/Skyrat-TG#25738]
Reporting client version: 515.1621

## Round ID:
10178

## Testmerges:
- [Antagonist Opt In](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24381)

## Reproduction:
Go to cargo, use the Supply (or Supply Request) console.
Open the Company Import tabs
Pick a company
Click on any item they sell
crash

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bvertical-align%2C%20horizontal-align%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at Za (http://127.0.0.1:53225/tgui.bundle.js:9:58156)
   at It (http://127.0.0.1:53225/tgui.bundle.js:9:60206)
   at qt (http://127.0.0.1:53225/tgui.bundle.js:9:61526)
   at wr (http://127.0.0.1:53225/tgui.bundle.js:9:63907)
   at uo (http://127.0.0.1:53225/tgui.bundle.js:9:75723)
   at Eu (http://127.0.0.1:53225/tgui.bundle.js:9:120717)
   at pu (http://127.0.0.1:53225/tgui.bundle.js:9:114787)
   at id (http://127.0.0.1:53225/tgui.bundle.js:9:114721)
   at vs (http://127.0.0.1:53225/tgui.bundle.js:9:114574)
   at mu (http://127.0.0.1:53225/tgui.bundle.js:9:111600)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; wbxapp 1.0.0; Zoom 3.6.0)
State: {"ckey":"ur mom","interface":"CargoImportConsole","window":{"key":"[0x21015f6a]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-540

**Comment by Allfd** [comment]
Same issue, clearing the byond cache and reconnecting does not resolve.
