### ISSUE TITLE
tried to use an exosuit fab

### ISSUE THREAD

**Issue by Syilumi** [Skyrat-SS13/Skyrat-TG#28586]
## Issue Summary
TypeError: Can't call method on undefined
   at Ee.exports (http://127.0.0.1:54747/tgui.bundle.js:410:63675)
   at Ee.exports (http://127.0.0.1:54747/tgui.bundle.js:410:70649)
   at Anonymous function (http://127.0.0.1:54747/tgui.bundle.js:410:58091)
   at values (http://127.0.0.1:54747/tgui.bundle.js:410:114195)
   at re (http://127.0.0.1:54747/tgui.bundle.js:299:287641)
   at cc (http://127.0.0.1:54747/tgui.bundle.js:9:69143)
   at Fd (http://127.0.0.1:54747/tgui.bundle.js:9:126671)
   at Nd (http://127.0.0.1:54747/tgui.bundle.js:9:122014)
   at Fh (http://127.0.0.1:54747/tgui.bundle.js:9:121947)
   at jc (http://127.0.0.1:54747/tgui.bundle.js:9:121795)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"simbolitis","interface":"ExosuitFabricator","window":{"key":"[0x200e973]-main","size":null,"fancy":1,"locked":0}}

uh... this popped up when i tried to use an exosuit fab in the anyrdine lava base

**Comment by SpaceLoveSs13** [comment]
Did this pop up again? Have you tried restarting, updating your BYOND etc? I need more details for reproducing the same effect.

**Comment by Syilumi** [comment]
ouh sorry for the late response downloading the newest rn to see what happens

**Comment by Syilumi** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/assets/104273939/f0cf10fd-ac66-4029-97d9-212696722e07

this is what happened

**Comment by SpaceLoveSs13** [comment]
> Screen.Recording.2024-07-05.212708.mp4 
> this is what happened

Tested it myself, works fine. Make sure your BYOND is up to date. Clean cache

**Comment by Syilumi** [comment]
bleh im too tired
