### ISSUE TITLE
Random NTOS crashes almost every round.

### ISSUE THREAD

**Issue by cmancini5493** [Skyrat-SS13/Skyrat-tg#4002]
Reporting client version: 514.1549

## Round ID:
945

## Testmerges:
- [[Modular] Ports Integrated Electronics (custom circuitry)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3429)
- [Sizeplay v 0.5](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255)
- [[Modular] Reproductive integration test](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3845)
- [Malorian Arms 3516 and Johnny Robohand bundle](https://github.com/Skyrat-SS13/Skyrat-tg/pull/3984)

## Reproduction:

UnhandledRejection: Error: Out of memory
   at Anonymous function (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:217094)
   at l (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:198632)
   at o (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:198430)
   at Anonymous function (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:199072)
   at n (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:214627)
   at a (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:214840)
   at Anonymous function (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:76131)
   at r (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:30860)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"theval","window":{"fancy":0,"locked":0}}

UnhandledRejection: Error: Out of memory
   at Anonymous function (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:217094)
   at l (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:198632)
   at o (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:198430)
   at Anonymous function (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:199072)
   at n (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:214627)
   at a (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:214840)
   at Anonymous function (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:76131)
   at r (http://127.0.0.1:62961/tmp21212/tgui-common.bundle.js:1:30860)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"theval","window":{"fancy":0,"locked":0}}

Nanotrasen (c) 2525-2561

**Comment by tf-4** [comment]
Closing for being very stale. Feel free to open if it's still an issue.
